name: deliver_ease
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_verification_code: ^1.1.0
  animate_do: ^3.3.3
  image_picker: ^1.0.7



  cupertino_icons: ^1.0.2
  phone_form_field: ^9.0.4
  jwt_decoder: ^2.0.1
  bloc: ^8.1.2
  equatable: ^2.0.5
  flutter_secure_storage: ^9.0.0
  api_cache_manager: ^1.0.2
  snippet_coder_utils: ^1.0.14
  http: ^1.2.0
  sqflite_common_ffi: ^2.3.2+1
  jwt_decode: ^0.3.1
  dart_jsonwebtoken: ^2.13.0
  auto_route: ^7.8.4
  flutter_dotenv: ^5.1.0
  mockito: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.1


flutter:


  uses-material-design: true


  assets:
    - assets/images/
    - assets/fonts/


  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Black.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Black.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montesserat/Montserrat-Black.ttf
        - asset: assets/fonts/montesserat/Montserrat-Bold.ttf
        - asset: assets/fonts/montesserat/Montserrat-Regular.ttf
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Black.ttf
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf

